// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64CCbT8CjkoTSbsgjXBgznwW36E-fJvk',
    appId: '1:576064303744:web:88e4c57f45e142f500ac65',
    messagingSenderId: '576064303744',
    projectId: 'pokedex-9d24c',
    authDomain: 'pokedex-9d24c.firebaseapp.com',
    storageBucket: 'pokedex-9d24c.appspot.com',
    measurementId: 'G-TWL2D5NCVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLo80HhXhKvidApt1SR5x4NyrXv71Qjhs',
    appId: '1:576064303744:android:4e1c7f47bbccc49a00ac65',
    messagingSenderId: '576064303744',
    projectId: 'pokedex-9d24c',
    storageBucket: 'pokedex-9d24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpVky6hu8JhpXqOMLvwTrWyFncnxTRek',
    appId: '1:576064303744:ios:128980d6c86ca36700ac65',
    messagingSenderId: '576064303744',
    projectId: 'pokedex-9d24c',
    storageBucket: 'pokedex-9d24c.appspot.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpVky6hu8JhpXqOMLvwTrWyFncnxTRek',
    appId: '1:576064303744:ios:39729ca79eee9b0800ac65',
    messagingSenderId: '576064303744',
    projectId: 'pokedex-9d24c',
    storageBucket: 'pokedex-9d24c.appspot.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
